""" Create a standard load profile with __init__() method.

Revision ID: 03422cb9c237
Revises: e5fbb1f1208a
Create Date: 2020-01-27 11:02:31.722829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03422cb9c237'
down_revision = 'e5fbb1f1208a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loadprofile',
    sa.Column('date', sa.String(length=33), nullable=False),
    sa.Column('time', sa.String(length=33), nullable=False),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'time')
    )
    op.drop_table('load_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_profile',
    sa.Column('date', sa.VARCHAR(length=33), nullable=False),
    sa.Column('time', sa.VARCHAR(length=33), nullable=False),
    sa.Column('energy', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'time')
    )
    op.drop_table('loadprofile')
    # ### end Alembic commands ###
