""" Create load profile.

Revision ID: 3524888ff528
Revises: 03422cb9c237
Create Date: 2020-01-27 11:24:34.250906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3524888ff528'
down_revision = '03422cb9c237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_profile',
                    sa.Column('date', sa.String(length=33), nullable=False),
                    sa.Column('time', sa.String(length=33), nullable=False),
                    sa.Column('energy', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('date', 'time')
                    )
    op.drop_table('loadprofile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loadprofile',
                    sa.Column('date', sa.VARCHAR(length=33), nullable=False),
                    sa.Column('time', sa.VARCHAR(length=33), nullable=False),
                    sa.Column('energy', sa.FLOAT(), nullable=True),
                    sa.PrimaryKeyConstraint('date', 'time')
                    )
    op.drop_table('load_profile')
    # ### end Alembic commands ###
