""" Add baseline state to user table.

Revision ID: 3d858c480257
Revises: 9a943d3917bf
Create Date: 2020-04-30 14:56:15.623037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d858c480257'
down_revision = '9a943d3917bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('baseline_sate', sa.Enum('WAITING_FOR_DATA', 'NO_READINGS_AVAILABLE', 'READY', name='baselinestatetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'baseline_sate')
    # ### end Alembic commands ###
