"""empty message

Revision ID: df2b5af9e9de
Revises: 67a4de7f7cf1
Create Date: 2020-04-16 12:10:31.918353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2b5af9e9de'
down_revision = '67a4de7f7cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registration_date')
    # ### end Alembic commands ###
